import { UserProfile, OrderItem, ManagedUser, DepositRequest, WithdrawalRequest, PlatformSettings } from './types';

export const initialUser: UserProfile = {
  id: 'usr_8829104',
  username: 'test1',
  email: 'admin@lifvox.com',
  balance: 0.00,
  frozenBalance: 0.00,
  vipLevel: 1,
  vipName: 'VIP 1 - Bronze',
  commissionRate: 0.04, // 4%
  completedOrdersCount: 0,
  targetOrdersCount: 24,
  referralCode: 'INVPYPJK8BY',
  isVerified: false,
  avatarText: 'TE',
  unreadNotifications: 1,
  isAdmin: false,
  status: 'active',
  joinedDate: '2026-08-15',
};

export const mockAdminUser: UserProfile = {
  id: 'usr_admin_001',
  username: 'Super Admin',
  email: 'admin@gmail.com',
  balance: 50000.00,
  frozenBalance: 0.00,
  vipLevel: 6,
  vipName: 'VIP 6 - Master Admin',
  commissionRate: 0.08,
  completedOrdersCount: 150,
  targetOrdersCount: 200,
  referralCode: 'ADMINVIP888',
  isVerified: true,
  avatarText: 'AD',
  unreadNotifications: 5,
  isAdmin: true,
  status: 'active',
  joinedDate: '2026-01-01',
};

export const initialManagedUsers: ManagedUser[] = [
  {
    id: 'usr_1001',
    username: 'rahim_trader',
    email: 'rahim@gmail.com',
    balance: 1450.00,
    frozenBalance: 0.00,
    vipLevel: 2,
    vipName: 'VIP 2 - Silver',
    commissionRate: 0.045,
    completedOrdersCount: 38,
    isVerified: true,
    status: 'active',
    joinedDate: '2026-08-10',
    totalDeposited: 2000.00,
    totalWithdrawn: 650.00,
  },
  {
    id: 'usr_1002',
    username: 'sarah_khan',
    email: 'sarah.k@yahoo.com',
    balance: 320.50,
    frozenBalance: 50.00,
    vipLevel: 1,
    vipName: 'VIP 1 - Bronze',
    commissionRate: 0.04,
    completedOrdersCount: 19,
    isVerified: true,
    status: 'active',
    joinedDate: '2026-08-14',
    totalDeposited: 500.00,
    totalWithdrawn: 200.00,
  },
  {
    id: 'usr_1003',
    username: 'tanvir_pro',
    email: 'tanvir99@gmail.com',
    balance: 4890.00,
    frozenBalance: 0.00,
    vipLevel: 3,
    vipName: 'VIP 3 - Gold',
    commissionRate: 0.05,
    completedOrdersCount: 65,
    isVerified: true,
    status: 'active',
    joinedDate: '2026-08-01',
    totalDeposited: 6000.00,
    totalWithdrawn: 1500.00,
  },
  {
    id: 'usr_1004',
    username: 'john_doe',
    email: 'john.d@outlook.com',
    balance: 85.00,
    frozenBalance: 0.00,
    vipLevel: 1,
    vipName: 'VIP 1 - Bronze',
    commissionRate: 0.04,
    completedOrdersCount: 8,
    isVerified: false,
    status: 'active',
    joinedDate: '2026-08-17',
    totalDeposited: 100.00,
    totalWithdrawn: 0.00,
  },
  {
    id: 'usr_1005',
    username: 'crypto_boss',
    email: 'boss@cryptomail.com',
    balance: 12400.00,
    frozenBalance: 1200.00,
    vipLevel: 4,
    vipName: 'VIP 4 - Platinum',
    commissionRate: 0.06,
    completedOrdersCount: 112,
    isVerified: true,
    status: 'active',
    joinedDate: '2026-07-20',
    totalDeposited: 15000.00,
    totalWithdrawn: 4000.00,
  },
  {
    id: 'usr_1006',
    username: 'suspicious_user',
    email: 'fake.bot@mail.ru',
    balance: 0.00,
    frozenBalance: 250.00,
    vipLevel: 1,
    vipName: 'VIP 1 - Bronze',
    commissionRate: 0.04,
    completedOrdersCount: 2,
    isVerified: false,
    status: 'frozen',
    joinedDate: '2026-08-18',
    totalDeposited: 250.00,
    totalWithdrawn: 0.00,
  },
];

export const initialDepositRequests: DepositRequest[] = [
  {
    id: 'dep_901',
    userId: 'usr_1001',
    username: 'rahim_trader',
    email: 'rahim@gmail.com',
    amount: 500.00,
    network: 'USDT (TRC-20)',
    txHash: '0x8f7d9a12c3b4e5f67890abcdef1234567890abcdef1234567890abcdef1234',
    status: 'pending',
    createdAt: '10 mins ago',
    notes: 'User submitted proof of transfer',
  },
  {
    id: 'dep_902',
    userId: 'usr_1004',
    username: 'john_doe',
    email: 'john.d@outlook.com',
    amount: 200.00,
    network: 'USDT (TRC-20)',
    txHash: '0x3a4b5c6d7e8f90123456789abcdef1234567890abcdef1234567890abcdef12',
    status: 'pending',
    createdAt: '25 mins ago',
  },
  {
    id: 'dep_903',
    userId: 'usr_1003',
    username: 'tanvir_pro',
    email: 'tanvir99@gmail.com',
    amount: 1500.00,
    network: 'USDT (BEP-20)',
    txHash: '0x99887766554433221100aabbccddeeff00112233445566778899aabbccddeeff',
    status: 'approved',
    createdAt: '2 hours ago',
  },
];

export const initialWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'wth_701',
    userId: 'usr_1002',
    username: 'sarah_khan',
    email: 'sarah.k@yahoo.com',
    amount: 150.00,
    network: 'USDT (TRC-20)',
    walletAddress: 'TYD2v7wM4Uq8vYx1zNkLpQ9wEx8v5J3K7L',
    status: 'pending',
    createdAt: '15 mins ago',
  },
  {
    id: 'wth_702',
    userId: 'usr_1005',
    username: 'crypto_boss',
    email: 'boss@cryptomail.com',
    amount: 2500.00,
    network: 'USDT (TRC-20)',
    walletAddress: 'TQx9L2kM7Vp4vYx3zNkLpQ9wEx8v5J3K9P',
    status: 'pending',
    createdAt: '40 mins ago',
  },
  {
    id: 'wth_703',
    userId: 'usr_1001',
    username: 'rahim_trader',
    email: 'rahim@gmail.com',
    amount: 300.00,
    network: 'USDT (TRC-20)',
    walletAddress: 'TNkLpQ9wEx8v5J3K7LTYD2v7wM4Uq8vYx1z',
    status: 'approved',
    createdAt: '3 hours ago',
    processedAt: '2 hours ago',
  },
];

export const defaultPlatformSettings: PlatformSettings = {
  minWithdrawal: 10,
  maxDailyOrders: 30,
  vipRates: [
    { level: 1, name: 'VIP 1 - Bronze', rate: 0.04, minDeposit: 20 },
    { level: 2, name: 'VIP 2 - Silver', rate: 0.045, minDeposit: 500 },
    { level: 3, name: 'VIP 3 - Gold', rate: 0.05, minDeposit: 2000 },
    { level: 4, name: 'VIP 4 - Platinum', rate: 0.06, minDeposit: 5000 },
    { level: 5, name: 'VIP 5 - Emerald', rate: 0.07, minDeposit: 10000 },
    { level: 6, name: 'VIP 6 - Diamond', rate: 0.08, minDeposit: 25000 },
  ],
  maintenanceMode: false,
  announcement: 'SellvoraPro Official: VIP commission rebates credited instantly upon order completion.',
};

export const sampleProducts = [
  {
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
    platform: 'Amazon' as const,
    minPrice: 85,
    maxPrice: 380,
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm Smartwatch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80',
    platform: 'Amazon' as const,
    minPrice: 120,
    maxPrice: 420,
  },
  {
    name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&auto=format&fit=crop&q=80',
    platform: 'eBay' as const,
    minPrice: 90,
    maxPrice: 350,
  },
  {
    name: 'DJI Mini 3 Lightweight Camera Drone 4K HDR',
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=500&auto=format&fit=crop&q=80',
    platform: 'eBay' as const,
    minPrice: 150,
    maxPrice: 480,
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra OLED Display 256GB',
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500&auto=format&fit=crop&q=80',
    platform: 'Shopify' as const,
    minPrice: 200,
    maxPrice: 650,
  },
  {
    name: 'Nike Air Zoom Pegasus 40 Running Shoes Edition',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80',
    platform: 'AliExpress' as const,
    minPrice: 45,
    maxPrice: 160,
  },
];

export const liveCommissionFeed = [
  { user: 'T***********6', amount: 432.10, time: 'Just now' },
  { user: 'K***********9', amount: 185.50, time: '1 min ago' },
  { user: 'M***********2', amount: 620.00, time: '2 mins ago' },
  { user: 'A***********8', amount: 94.20, time: '3 mins ago' },
  { user: 'R***********1', amount: 312.80, time: '4 mins ago' },
  { user: 'D***********4', amount: 550.00, time: '5 mins ago' },
];

export const faqsList = [
  {
    q: 'How do I start earning commissions on Lifvox / SellvoraPro?',
    a: 'Simply fund your balance with USDT (TRC-20 or ERC-20), choose an e-commerce partner platform (Amazon, eBay, etc.), click "Grab Order", confirm the product order dispatch, and your commission will be credited directly to your balance.',
  },
  {
    q: 'What are the VIP tiers and commission rates?',
    a: 'VIP 1 Bronze grants 4.0% per order (20 - 498 USDT range). VIP 2 Silver grants 4.5% per order (500 - 1999 USDT). VIP 3 Gold grants 5.0% per order (2000 - 4999 USDT). As your volume grows, your daily earnings increase!',
  },
  {
    q: 'How fast are withdrawal requests processed?',
    a: 'Withdrawals are processed around the clock via automated blockchain settlement. Typical delivery times are under 10 minutes to your verified USDT wallet address.',
  },
  {
    q: 'Can I invite friends and earn referral bonuses?',
    a: 'Yes! Share your personal invitation code. You will earn multi-tier commissions on orders placed by your direct and extended team members.',
  },
  {
    q: 'Is there a minimum deposit and withdrawal limit?',
    a: 'The minimum initial account activation is 20 USDT, and the minimum withdrawal threshold is 10 USDT with low standard network gas fees.',
  },
];
